version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: local
      HOST: 0.0.0.0
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: task-management
      DATABASE_URL_WITHOUT_SCHEMA: postgresql://postgres:postgres@db:5432
      DATABASE_URL: postgresql://postgres:postgres@db:5432/task-management
      DATABASE_URL_NON_POOLING: postgresql://postgres:postgres@db:5432/task-management
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: